language: scala

scala:
  - 2.11.8

dist: trusty

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers

script:
  - ./sbt test
  - ./sbt it:test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
