language: scala

scala:
  - 2.11.8

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - shellcheck

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers
    - $HOME/.coursier

script:
  - ./ci.sh

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)
